backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Blog" # Used in the UI
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "src/pages/blog/{{slug}}" # Path to the preview template for this collection
    sortable_fields: ['commit_date', 'title', 'commit_author', 'publishDate']
    view_groups:
      - label: Publish Date
        field: publishDate
        # groups items based on the value matched by the pattern
        pattern: \d{4}
      - label: Drafts
        field: draft
      - label: Authors
        field: author
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "snippet", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm"}
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "team"
        search_fields: ["name"]
        value_field: "name"
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "admin"
        file: "options"
        multiple: true
        min: 1
        value_field: "categories.*"
        search_fields: ["categories.*"]
      # - {label: "Category", name: "category", widget: "string"}
      # - {label: "Categories", name: "categories", widget: "string-array"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, default: ["blog"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "draft", name: "draft",  widget: "hidden", default: false}
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - {label: Alt, name: alt, widget: string}
          - {label: Image, name: src, widget: image}
  - label: "Team" # Used in the UI
    name: "team" # Used in routes, e.g., /admin/collections/blog
    folder: "src/content/team" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    # extension: md
    identifier_field: name
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm"}
      - {label: "draft", name: "draft",  widget: "hidden", default: false}
      - label: "Avatar"
        name: "avatar"
        widget: "object"
        fields:
          - {label: Alt, name: alt, widget: string}
          - {label: Avatar, name: src, widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Prices" # Used in the UI
    name: "prices" # Used in routes, e.g., /admin/collections/blog
    folder: "src/content/prices" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}-{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "draft", name: "draft",  widget: "hidden", default: false}
      - {label: "Name", name: "name", widget: "string"}
      - label: "Type"
        name: "type"
        widget: "select"
        options:
          - {label: Hourly, value: hourly}
          - {label: Monthly, value: monthly}
          - {label: Annual, value: annual}
          - {label: Custom, value: custom}
        default: monthly
      - label: "Price"
        name: "price"
        widget: "object"
        fields:
          - {label: "Current", name: current, widget: number, required: false}
          - {label: "Previous", name: previous, widget: number, required: false}
      - {label: "Currency", name: "currency", widget: "string", default: "$"}
      - {label: "Popular", name: "popular",  widget: "boolean", default: false}
      - {label: "Features", name: "features", widget: "string-array"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm"}
      - {label: "Expiration Date", name: "expirationDate", widget: "datetime", default: "", date_format: "YYYY-MM-DD", time_format: "HH:mm", required: false}
      - {label: "Order", name: "order",  widget: "number", required: false}
      - label: "Button"
        name: "button"
        widget: "object"
        fields:
          - {label: "Text", name: "text", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
  - label: "Admin"
    name: "admin"
    files:
    - label: "Options"
      name: "options"
      file: "public/admin/options.yml"
      fields: # The fields for each document, usually in front matter
        - {label: "Categories", name: "categories", widget: "string-array"}
