backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "src/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "blog/{{slug}}" # Path to the preview template for this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, default: ["blog"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Description", name: "snippet", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "draft", name: "draft",  widget: "hidden", default: false}
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
        - {label: Alt, name: alt, widget: string}
        - {label: Image, name: src, widget: image}
      